spring:
  cloud:
    stream:
      kafka:
        bindings:
          disabledAllWalletConnects-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
              compression-type: zstd
        binder:
          brokers:
            - localhost:9092
            - localhost:9093
            - localhost:9094
      bindings:
        disabledAllWalletConnects-out-0:
          destination: test
          content-type: application/json
