spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
            - localhost:9093
            - localhost:9094
      bindings:
        disabledAllWalletConnects-out-0:
          destination: test
          content-type: application/json
